---
- name: Check the SBD LUN image file
  ansible.builtin.stat:
    path: "{{ iscsi_target_lun_img }}"
  register: iscsi_target_lun_stat
  tags: [iscsi, target, lun]

- name: Prepare the SBD LUN storage directory
  ansible.builtin.file:
    path: "{{ iscsi_target_lun_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when:
    - not iscsi_target_lun_stat.stat.exists
    - not ansible_check_mode
  tags: [iscsi, target, lun]

- name: Create the small SBD LUN image
  ansible.builtin.command:
    cmd: truncate -s {{ iscsi_target_lun_size }} {{ iscsi_target_lun_img }}
    creates: "{{ iscsi_target_lun_img }}"
  when:
    - not iscsi_target_lun_stat.stat.exists
    - not ansible_check_mode
  tags: [iscsi, target, lun]
