---
- name: Sertakan langkah instalasi paket target iSCSI
  ansible.builtin.import_tasks: install.yml
  tags: [iscsi, target, install]

- name: Sertakan langkah penyediaan LUN SBD
  ansible.builtin.import_tasks: lun.yml
  tags: [iscsi, target, lun]

- name: Sertakan langkah konfigurasi targetcli
  ansible.builtin.import_tasks: targetcli.yml
  tags: [iscsi, target, targetcli]

- name: Sertakan langkah aktivasi layanan target
  ansible.builtin.import_tasks: service.yml
  tags: [iscsi, target, service]

- name: Sertakan langkah verifikasi target iSCSI
  ansible.builtin.import_tasks: verify.yml
  tags: [iscsi, target, verify]
