---
- name: Sertakan langkah berkas meta eksternal DRBD
  ansible.builtin.import_tasks: meta_loop.yml
  tags: [drbd, resource, meta]

- name: Sertakan langkah definisi resource kin-zimbra
  ansible.builtin.import_tasks: resource_file.yml
  tags: [drbd, resource, config]

- name: Sertakan langkah aktivasi DRBD (mutasi — hati-hati)
  ansible.builtin.import_tasks: activate.yml
  tags: [drbd, resource, activate]

- name: Sertakan langkah verifikasi resource DRBD
  ansible.builtin.import_tasks: verify.yml
  tags: [drbd, resource, verify]
