---
- name: Enable the qnetd service at boot
  ansible.builtin.systemd:
    name: "{{ corosync_qnetd_service }}"
    enabled: true
  tags: [qnetd, service]

- name: Start the qnetd service
  ansible.builtin.systemd:
    name: "{{ corosync_qnetd_service }}"
    state: started
  tags: [qnetd, service]
