---
- name: Include the external meta steps on the new node
  ansible.builtin.import_tasks: meta_loop.yml
  tags: [drbd, livejoin, meta]

- name: Include the resource definition steps on the new node
  ansible.builtin.import_tasks: resource_file.yml
  tags: [drbd, livejoin, config]

- name: Include the connect and full sync steps to the live Primary
  ansible.builtin.import_tasks: connect.yml
  tags: [drbd, livejoin, connect]

- name: Include the DRBD sync status verification
  ansible.builtin.import_tasks: verify.yml
  tags: [drbd, livejoin, verify]
