---
- name: Enable the open-iscsi service at boot
  ansible.builtin.systemd:
    name: open-iscsi
    enabled: true
  tags: [iscsi, initiator, service]

- name: Start the open-iscsi service
  ansible.builtin.systemd:
    name: open-iscsi
    state: started
  tags: [iscsi, initiator, service]
