---
- name: Enable the qdevice service at boot
  ansible.builtin.systemd:
    name: "{{ corosync_qdevice_service }}"
    enabled: true
  tags: [qdevice, service]

- name: Start the qdevice service
  ansible.builtin.systemd:
    name: "{{ corosync_qdevice_service }}"
    state: started
  tags: [qdevice, service]
