---
- name: Sertakan langkah instalasi paket DRBD
  ansible.builtin.import_tasks: packages.yml
  tags: [drbd, install, packages]

- name: Sertakan langkah pemuatan modul DRBD
  ansible.builtin.import_tasks: module.yml
  tags: [drbd, install, module]

- name: Sertakan langkah verifikasi instalasi DRBD
  ansible.builtin.import_tasks: verify.yml
  tags: [drbd, install, verify]
