#!/usr/bin/env bash
# KIN Mail - generate the file that installs Zimbra without a terminal.
#
# Zimbra's installer takes a defaults file as a positional argument. Given one,
# it sources the file, skips every package prompt because the answers are
# already there, installs what INSTALL_PACKAGES names, and then hands the SAME
# file to zmsetup.pl -c. One file per machine is therefore the whole difference
# between a mailbox node and an edge node.
#
# The file is plain shell, sourced as root by the installer, and it carries the
# LDAP passwords. It is written 0600 and deleted by the caller; nothing here
# echoes a secret.
#
# Verified against zcs-10.1.20 (UBUNTU22_64) by check-unattended-install.sh:
# install.sh:143 reads DEFAULTFILE, :209 loads it, :343 passes it to zmsetup.pl.
# Key names come from that build's zmsetup.pl, not from documentation - this
# build spells most of them upper case but ldap_nginx_password lower, and
# guessing either way produces a file that is accepted and then ignored.

# Packages per role.
#
# zimbra-memcached is NOT in the tarball - it comes from Zimbra's apt
# repository, which is why stage 03 pre-seeds the packaging key. Naming it here
# is correct; the installer fetches it.
#
# zimbra-logger goes on the mailbox because it owns the logger database, and
# only one node may run it.
KIN_ZCS_PACKAGES_MAILBOX="zimbra-core zimbra-ldap zimbra-store zimbra-apache zimbra-spell zimbra-logger zimbra-snmp"
KIN_ZCS_PACKAGES_EDGE="zimbra-core zimbra-mta zimbra-proxy zimbra-memcached zimbra-snmp"

# kin_zcs_common_defaults
#
# The half of the file that is the same on both machines. Printed to stdout.
kin_zcs_common_defaults() {
  cat <<EOF
# Generated by KIN Mail. Sourced by Zimbra's installer; contains secrets.
INSTALL_WEBAPPS="service zimlet zimbra zimbraAdmin"
SERVICEWEBAPP="yes"
UIWEBAPPS="yes"
MODE="https"
zimbraIPMode="ipv4"
HTTPPORT="8080"
HTTPSPORT="8443"
IMAPPORT="7143"
POPPORT="7110"
SMTPHOST="${MAILBOX_HOST}"
AVDOMAIN="${MAIL_DOMAIN}"
AVUSER="admin@${MAIL_DOMAIN}"
zimbraDefaultDomainName="${MAIL_DOMAIN}"
zimbraPrefTimeZoneId="${ZIMBRA_TZ_NAME:-Asia/Bangkok}"
SNMPNOTIFY="no"
SNMPTRAPHOST="${MAILBOX_HOST}"
# Telemetry off. The interactive installer asks this as "Notify Zimbra of your
# installation?" and answering yes mails the admin address to Zimbra.
VERSIONUPDATECHECKS="FALSE"
zimbraVersionCheckSendNotifications="FALSE"
STARTSERVERS="yes"
# UPGRADE and REMOVE are deliberately NOT set here.
#
# They look like answers but they are install.sh's own findings: utilfunc.sh
# works out whether this is an upgrade by inspecting what is already on the
# machine (lines ~1360-1389). Setting UPGRADE="yes" in this file overrides that
# detection, so a clean machine logs every package as UPGRADED rather than
# INSTALLED. zmsetup then computes newinstall = 0 from zimbra-core's history
# entry (zmsetup.pl:1893), and newinstall is what gates zmldapinit - so the
# directory is never created, and every later step fails with an LDAP
# "Connection refused" that has nothing to do with LDAP.
#
# Cost one full reinstall to find, 16 September 2026. Do not add them back.
LDAPPORT="389"
LDAPHOST="${MAILBOX_HOST}"
ldap_url="ldap://${MAILBOX_HOST}:389"
EOF
}

# kin_zcs_ldap_secret
#
# One directory password. Letters and digits only, deliberately: Zimbra's own
# installer rejects several metacharacters in passwords, and these values are
# also pasted through shell single quotes inside zmsetup, so the safe set is
# the boring one.
kin_zcs_ldap_secret() {
  LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
}

# kin_zcs_ensure_ldap_secrets [store]
#
# Populate KIN_LDAP_* with this deployment's directory passwords, generating
# them once and reusing them afterwards.
#
# They have to be decided HERE rather than left to Zimbra. zmsetup passes
# LDAPROOTPASS and LDAPADMINPASS straight into zmldapinit when it creates the
# directory (zmsetup.pl:5451), so leaving them empty does not mean "generate
# one" - it means initialise the directory with an empty password. The edge
# then has nothing to join with either.
#
# Stored 0600 next to the appliance config so a re-run, or the edge build that
# happens minutes later, reuses the same values instead of minting a second set
# the directory has never heard of.
kin_zcs_ensure_ldap_secrets() {
  local store="${1:-${CONF_DIR:-/etc/kin-mail}/ldap-secrets}"

  if [ -r "$store" ]; then
    # shellcheck disable=SC1090
    . "$store"
  fi

  local name
  for name in KIN_LDAP_ADMIN_PASS KIN_LDAP_ROOT_PASS KIN_LDAP_REP_PASS \
              KIN_LDAP_POST_PASS KIN_LDAP_AMAVIS_PASS KIN_LDAP_NGINX_PASS; do
    if [ -z "${!name:-}" ]; then
      printf -v "$name" '%s' "$(kin_zcs_ldap_secret)"
    fi
  done

  local dir
  dir=$(dirname "$store")
  mkdir -p "$dir" 2>/dev/null || true
  ( umask 077; cat >"$store" <<EOF
# KIN Mail - this deployment's Zimbra directory passwords.
# Generated once; both machines must present the same values or the edge
# cannot bind to the mailbox's directory.
KIN_LDAP_ADMIN_PASS='${KIN_LDAP_ADMIN_PASS}'
KIN_LDAP_ROOT_PASS='${KIN_LDAP_ROOT_PASS}'
KIN_LDAP_REP_PASS='${KIN_LDAP_REP_PASS}'
KIN_LDAP_POST_PASS='${KIN_LDAP_POST_PASS}'
KIN_LDAP_AMAVIS_PASS='${KIN_LDAP_AMAVIS_PASS}'
KIN_LDAP_NGINX_PASS='${KIN_LDAP_NGINX_PASS}'
EOF
  )
  chmod 600 "$store" 2>/dev/null || true
}

# kin_zcs_defaults_mailbox <outfile>
#
# The first machine. It becomes the LDAP master: it creates the directory, the
# domain and the admin account, and it holds the mail. Nothing joins anything
# here - there is nothing to join yet.
#
# The directory passwords ARE set here. zmsetup hands LDAPROOTPASS and
# LDAPADMINPASS to zmldapinit when it creates the directory, so an empty value
# creates a directory with an empty password rather than a generated one.
kin_zcs_defaults_mailbox() {
  local out="$1"
  : >"$out"
  chmod 600 "$out"
  {
    kin_zcs_common_defaults
    cat <<EOF
INSTALL_PACKAGES="${KIN_ZCS_PACKAGES_MAILBOX}"
HOSTNAME="${MAILBOX_HOST}"
zimbra_server_hostname="${MAILBOX_HOST}"
LDAPREPLICATIONTYPE="master"
LDAPSERVERID="2"
LDAPADMINPASS="${KIN_LDAP_ADMIN_PASS}"
LDAPADMINPASSSET="yes"
LDAPROOTPASS="${KIN_LDAP_ROOT_PASS}"
LDAPROOTPASSSET="yes"
LDAPREPPASS="${KIN_LDAP_REP_PASS}"
LDAPREPPASSSET="yes"
LDAPPOSTPASS="${KIN_LDAP_POST_PASS}"
LDAPPOSTPASSSET="yes"
LDAPAMAVISPASS="${KIN_LDAP_AMAVIS_PASS}"
LDAPAMAVISPASSSET="yes"
ldap_nginx_password="${KIN_LDAP_NGINX_PASS}"
LDAPNGINXPASSSET="yes"
CREATEDOMAIN="${MAIL_DOMAIN}"
CREATEADMIN="admin@${MAIL_DOMAIN}"
CREATEADMINPASS="${ADMIN_PASS}"
# This node answers proxy route lookups and accepts authenticated submission
# relayed from the edge.
zimbraReverseProxyLookupTarget="TRUE"
zimbraMtaAuthTarget="TRUE"
MAILBOXDMEMORY="${KIN_ZCS_MAILBOXD_MEMORY:-4096}"
MYSQLMEMORYPERCENT="${KIN_ZCS_MYSQL_PERCENT:-30}"
USESPELL="yes"
SPELLURL="http://${MAILBOX_HOST}:7780/aspell.php"
EOF
  } >>"$out"
}

# kin_zcs_defaults_edge <outfile>
#
# The second machine. It installs no store and no directory: it binds to the
# mailbox's LDAP over the network, which is why every password below has to be
# the one the mailbox actually minted rather than a fresh one.
#
# Each password has a matching *SET flag. Without the flag zmsetup treats the
# value as unset and generates its own, which produces a node that installs
# cleanly and then cannot bind - the failure appears later, as mail not moving.
kin_zcs_defaults_edge() {
  local out="$1"
  : >"$out"
  chmod 600 "$out"
  {
    kin_zcs_common_defaults
    cat <<EOF
INSTALL_PACKAGES="${KIN_ZCS_PACKAGES_EDGE}"
HOSTNAME="${EDGE_HOST}"
zimbra_server_hostname="${EDGE_HOST}"
LDAPREPLICATIONTYPE="none"
LDAPADMINPASS="${KIN_LDAP_ADMIN_PASS}"
LDAPADMINPASSSET="yes"
LDAPROOTPASS="${KIN_LDAP_ROOT_PASS}"
LDAPROOTPASSSET="yes"
LDAPREPPASS="${KIN_LDAP_REP_PASS}"
LDAPREPPASSSET="yes"
LDAPPOSTPASS="${KIN_LDAP_POST_PASS}"
LDAPPOSTPASSSET="yes"
LDAPAMAVISPASS="${KIN_LDAP_AMAVIS_PASS}"
LDAPAMAVISPASSSET="yes"
ldap_nginx_password="${KIN_LDAP_NGINX_PASS}"
LDAPNGINXPASSSET="yes"
# The domain and admin already exist in the mailbox's directory. Creating them
# again from here is how a second, conflicting domain entry appears.
CREATEDOMAIN="no"
CREATEADMIN="no"
# This node proxies; it does not answer route lookups and holds no mailboxes.
zimbraReverseProxyLookupTarget="FALSE"
zimbraMtaAuthTarget="FALSE"
PROXYMODE="https"
zimbraMailProxy="TRUE"
zimbraWebProxy="TRUE"
USESPELL="no"
EOF
  } >>"$out"
}

# kin_zcs_defaults_problem <file>
#
# Prints the first reason this generated file would not produce the node we
# meant, and returns 0; returns 1 when it looks right. Cheap to run, and the
# alternative is finding out after a twenty-minute install.
kin_zcs_defaults_problem() {
  local f="${1:-}" pkgs host
  [ -r "$f" ] || { printf 'defaults file %s is not readable\n' "$f"; return 0; }

  pkgs=$(sed -n 's/^INSTALL_PACKAGES="\(.*\)"$/\1/p' "$f")
  [ -n "$pkgs" ] || { printf 'no INSTALL_PACKAGES: the installer would stop at its package menu\n'; return 0; }
  case "$pkgs" in *zimbra-core*) ;; *) printf 'INSTALL_PACKAGES has no zimbra-core\n'; return 0 ;; esac

  host=$(sed -n 's/^HOSTNAME="\(.*\)"$/\1/p' "$f")
  [ -n "$host" ] || { printf 'no HOSTNAME\n'; return 0; }

  # A node that installs both the directory and the MTA is a single appliance,
  # not half of a split.
  case "$pkgs" in
    *zimbra-ldap*)
      case "$pkgs" in *zimbra-mta*)
        printf 'this file installs both zimbra-ldap and zimbra-mta: that is a single appliance, not a split node\n'
        return 0 ;;
      esac
      ;;
  esac

  # An edge without the passwords installs cleanly and then cannot bind. The
  # symptom is mail not moving, hours later.
  case "$pkgs" in
    *zimbra-mta* | *zimbra-proxy*)
      grep -q '^LDAPADMINPASSSET="yes"' "$f" || {
        printf 'joining node has no LDAPADMINPASSSET: it will mint its own password and fail to bind\n'; return 0; }
      grep -qE '^LDAPADMINPASS="..*"' "$f" || {
        printf 'joining node has an empty LDAPADMINPASS\n'; return 0; }
      ;;
  esac

  grep -q '^LDAPHOST="..*"' "$f" || { printf 'no LDAPHOST\n'; return 0; }
  return 1
}
