---
- name: Sertakan langkah instalasi paket resource-agents
  ansible.builtin.import_tasks: packages.yml
  tags: [pacemaker, agents, packages]

- name: Sertakan langkah pemasangan OCF Zimbra
  ansible.builtin.import_tasks: ocf.yml
  tags: [pacemaker, agents, ocf]

- name: Sertakan langkah skrip assert dual-primary
  ansible.builtin.import_tasks: assert.yml
  tags: [pacemaker, agents, assert]

- name: Sertakan langkah penyesuaian systemd DRBD
  ansible.builtin.import_tasks: systemd.yml
  tags: [pacemaker, agents, systemd]

- name: Sertakan langkah verifikasi agen Pacemaker
  ansible.builtin.import_tasks: verify.yml
  tags: [pacemaker, agents, verify]
