#!/usr/bin/env bash
# =============================================================================
# KIN Mail - 12 CUSTOMER BRANDING (Zimbra FOSS chameleon)
#
# Per-customer logo/theme for Zimbra webmail. Assets live in
# /etc/kin-mail/brand/ (owned by KIN Mail, not jetty skins/). Nginx serves
# them at /kin-brand/. LDAP chameleon attrs point at those URLs. Idempotent.
#
# Why this path (not Ansible, not the admin console, not a skins/ overlay):
#   - Same optional-stage pattern as 07-zpush / 08-create-mailbox / 11-admin-path.
#   - Customer identity is per-deploy, like MAIL_DOMAIN; apply without a full
#     reinstall. Re-run after a Zimbra upgrade that rewrites the nginx template.
#   - Console branding (KIN Mail admin UI) is a later slice (Timeline 6.3).
#   - Ansible HA roles should not own cosmetics; LDAP is on DRBD and is applied
#     once on the Promoted node. Peer OS copies use --os-only.
#
#   sudo ./12-branding.sh              # assets + nginx + LDAP (Promoted)
#   sudo ./12-branding.sh --os-only    # /etc/kin-mail/brand/ only (Unpromoted)
#   sudo ./12-branding.sh --dummy      # force bundled placeholder assets
#
# Override the asset directory:  KIN_BRAND_SOURCE=/path/with/brand.conf
# Skip mailboxd/proxy restart:   KIN_BRAND_SKIP_RESTART=1
# =============================================================================
set -u
cd "$(dirname "$0")" && . ./00-config.sh
need_root

OS_ONLY=0
FORCE_DUMMY=0
for arg in "$@"; do
  case "$arg" in
    --os-only) OS_ONLY=1 ;;
    --dummy) FORCE_DUMMY=1 ;;
    -h|--help)
      sed -n '2,24p' "$0"
      exit 0
      ;;
    *)
      fail "Unknown argument: ${arg}"
      info "Usage: $0 [--os-only] [--dummy]"
      exit 2
      ;;
  esac
done

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
DUMMY_SRC="${REPO_ROOT}/branding/dummy"
NGX_TPL="${NGX_TPL:-/opt/zimbra/conf/nginx/templates/nginx.conf.web.https.default.template}"
BRAND_DIR="/etc/kin-mail/brand"
SNIPPET="${BRAND_DIR}/nginx-kin-brand.conf"
PATCHER="${SCRIPT_DIR}/lib/kin_brand_nginx.py"

if [ "$FORCE_DUMMY" -eq 1 ]; then
  BRAND_SOURCE="$DUMMY_SRC"
else
  BRAND_SOURCE="${KIN_BRAND_SOURCE:-$DUMMY_SRC}"
fi

if [ ! -f "${BRAND_SOURCE}/brand.conf" ]; then
  fail "Brand source missing brand.conf: ${BRAND_SOURCE}"
  info "Bundle a directory with brand.conf + PNG/ICO files, or use --dummy."
  exit 1
fi
if [ ! -f "$PATCHER" ]; then
  fail "Missing nginx patcher: ${PATCHER}"
  exit 1
fi

# shellcheck disable=SC1091
. "${BRAND_SOURCE}/brand.conf"
: "${BRAND_NAME:=KIN Dummy Brand}"
: "${BRAND_URL:=https://example.invalid/kin-dummy-brand}"
: "${BRAND_ACCENT:=#C45C26}"
: "${BRAND_BACKGROUND:=#1B2430}"
: "${BRAND_FOREGROUND:=#F4EDE4}"
: "${BRAND_SECONDARY:=$BRAND_ACCENT}"
: "${BRAND_SELECTION:=#E07A3D}"
: "${BRAND_LOGIN_BANNER:=login-banner.png}"
: "${BRAND_APP_BANNER:=app-banner.png}"
: "${BRAND_FAVICON:=favicon.ico}"

LOGIN_URL="/kin-brand/${BRAND_LOGIN_BANNER}"
APP_URL="/kin-brand/${BRAND_APP_BANNER}"
FAV_URL="/kin-brand/${BRAND_FAVICON}"

echo
say "Customer branding → ${BRAND_DIR}"
info "Source : ${BRAND_SOURCE}"
info "Name   : ${BRAND_NAME}"
info "Accent : ${BRAND_ACCENT}"
if [ "$OS_ONLY" -eq 1 ]; then
  info "Mode   : --os-only (no nginx template, no LDAP)"
fi

# -----------------------------------------------------------------------------
install_brand_tree() {
  say "1. Install brand assets under ${BRAND_DIR}"
  mkdir -p "$BRAND_DIR"
  local f
  for f in brand.conf "$BRAND_LOGIN_BANNER" "$BRAND_APP_BANNER" "$BRAND_FAVICON"; do
    if [ ! -f "${BRAND_SOURCE}/${f}" ]; then
      fail "Missing ${f} in ${BRAND_SOURCE}"
      exit 1
    fi
    cp -f "${BRAND_SOURCE}/${f}" "${BRAND_DIR}/${f}"
  done
  cat >"$SNIPPET" <<EOF
# Generated by install/12-branding.sh — do not copy into jetty skins/.
alias ${BRAND_DIR}/;
add_header Cache-Control "public, max-age=300";
types {
    image/png png;
    image/x-icon ico;
    image/vnd.microsoft.icon ico;
    image/svg+xml svg;
}
default_type application/octet-stream;
access_log off;
EOF
  # Zimbra nginx runs as zimbra and must include + read this tree.
  chmod 755 "$BRAND_DIR"
  chmod 644 "$SNIPPET" "${BRAND_DIR}/brand.conf" \
    "${BRAND_DIR}/${BRAND_LOGIN_BANNER}" \
    "${BRAND_DIR}/${BRAND_APP_BANNER}" \
    "${BRAND_DIR}/${BRAND_FAVICON}"
  ok "Assets + nginx snippet in ${BRAND_DIR}"
}

# -----------------------------------------------------------------------------
patch_nginx_template() {
  say "2. Nginx HTTPS template → location ^~ /kin-brand/"
  if [ ! -f "$NGX_TPL" ]; then
    fail "Missing nginx HTTPS template: ${NGX_TPL}"
    info "Run on the Promoted node (DRBD mounted), or use --os-only on the peer."
    exit 1
  fi
  local py_out
  py_out=$(python3 "$PATCHER" "$NGX_TPL" "$SNIPPET") || {
    fail "template patch failed: ${py_out:-}"
    exit 1
  }
  if [ "$py_out" = "unchanged" ]; then
    ok "Template already serves /kin-brand/"
    NEED_PROXY=0
  else
    ok "Template patched (${py_out#changed:})"
    NEED_PROXY=1
  fi
}

# -----------------------------------------------------------------------------
ldap_get() {
  local scope="$1" attr="$2"
  su - zimbra -c "zmprov ${scope} ${attr}" 2>/dev/null | awk -F': ' -v a="$attr" '$1==a {print $2; exit}'
}

apply_chameleon_ldap() {
  say "3. LDAP chameleon attributes (Maldua FOSS 10.1.x)"
  if ! su - zimbra -c "zmprov desc -a zimbraSkinLogoLoginBanner" >/dev/null 2>&1; then
    fail "This Zimbra build has no zimbraSkinLogoLoginBanner — refusing a skins/ overlay."
    info "FOSS chameleon attrs were verified on Maldua 10.1.18; re-check zmprov desc."
    exit 1
  fi

  local need_ldap=0
  local cur
  cur=$(ldap_get "gacf" "zimbraSkinLogoLoginBanner")
  if [ "$cur" != "$LOGIN_URL" ]; then
    need_ldap=1
  fi
  cur=$(ldap_get "gd ${MAIL_DOMAIN}" "zimbraSkinLogoLoginBanner")
  if [ "$cur" != "$LOGIN_URL" ]; then
    need_ldap=1
  fi

  # Always set the full chameleon set. zmprov md/mcf is cheap and idempotent.
  # Path-absolute URLs so the browser resolves against the current origin
  # (VIP hostname or scratch IP) instead of a baked MAIL_HOST.
  if ! su - zimbra -c "zmprov mcf \
      zimbraSkinLogoLoginBanner '${LOGIN_URL}' \
      zimbraSkinLogoAppBanner '${APP_URL}' \
      zimbraSkinLogoURL '${BRAND_URL}' \
      zimbraSkinFavicon '${FAV_URL}' \
      zimbraSkinBackgroundColor '${BRAND_BACKGROUND}' \
      zimbraSkinForegroundColor '${BRAND_FOREGROUND}' \
      zimbraSkinSecondaryColor '${BRAND_SECONDARY}' \
      zimbraSkinSelectionColor '${BRAND_SELECTION}'"; then
    fail "zmprov mcf chameleon attrs failed"
    exit 1
  fi
  if ! su - zimbra -c "zmprov md '${MAIL_DOMAIN}' \
      zimbraSkinLogoLoginBanner '${LOGIN_URL}' \
      zimbraSkinLogoAppBanner '${APP_URL}' \
      zimbraSkinLogoURL '${BRAND_URL}' \
      zimbraSkinFavicon '${FAV_URL}' \
      zimbraSkinBackgroundColor '${BRAND_BACKGROUND}' \
      zimbraSkinForegroundColor '${BRAND_FOREGROUND}' \
      zimbraSkinSecondaryColor '${BRAND_SECONDARY}' \
      zimbraSkinSelectionColor '${BRAND_SELECTION}'"; then
    fail "zmprov md ${MAIL_DOMAIN} chameleon attrs failed"
    exit 1
  fi
  su - zimbra -c "zmprov fc all" >/dev/null 2>&1 || true
  NEED_MAILBOXD=1
  if [ "$need_ldap" -eq 0 ]; then
    info "LDAP values already matched; still flushing cache + mailboxd so skins pick them up"
  fi
  ok "gacf + domain ${MAIL_DOMAIN} chameleon attrs set"
}

# -----------------------------------------------------------------------------
restart_zimbra_frontends() {
  if [ "${KIN_BRAND_SKIP_RESTART:-0}" = "1" ]; then
    warn "KIN_BRAND_SKIP_RESTART=1 — skip zmproxy/zmmailboxd; run later or wait for cache"
    return 0
  fi
  if [ "${NEED_PROXY:-0}" -eq 0 ] && [ "${NEED_MAILBOXD:-0}" -eq 0 ]; then
    ok "No proxy/mailboxd restart needed"
    return 0
  fi
  say "4. Reload nginx template + mailboxd (kin-zimbra temporarily unmanaged)"
  kin_zimbra_unmanage
  trap kin_zimbra_remanage EXIT
  if [ "${NEED_PROXY:-0}" -eq 1 ]; then
    if ! su - zimbra -c "/opt/zimbra/libexec/zmproxyconfgen" >/tmp/kin-brand-confgen.out 2>&1; then
      fail "zmproxyconfgen failed — see /tmp/kin-brand-confgen.out"
      kin_zimbra_remanage
      trap - EXIT
      exit 1
    fi
    if ! su - zimbra -c "zmproxyctl restart" >/tmp/kin-brand-proxy.out 2>&1; then
      fail "zmproxyctl restart failed — see /tmp/kin-brand-proxy.out"
      kin_zimbra_remanage
      trap - EXIT
      exit 1
    fi
  fi
  if [ "${NEED_MAILBOXD:-0}" -eq 1 ]; then
    if ! su - zimbra -c "zmmailboxdctl restart" >/tmp/kin-brand-mailboxd.out 2>&1; then
      fail "zmmailboxdctl restart failed — see /tmp/kin-brand-mailboxd.out"
      kin_zimbra_remanage
      trap - EXIT
      exit 1
    fi
  fi
  if ! kin_zimbra_wait_healthy; then
    fail "Zimbra not healthy after branding restart"
    kin_zimbra_remanage
    trap - EXIT
    exit 1
  fi
  kin_zimbra_remanage
  trap - EXIT
  ok "Proxy/mailboxd healthy"
}

# -----------------------------------------------------------------------------
verify_brand() {
  say "5. Verify /kin-brand/ is served and LDAP matches"
  local code tmp
  tmp=$(mktemp)
  code=$(curl -sk -o "$tmp" -w '%{http_code}' --connect-timeout 5 --max-time 10 \
    "https://127.0.0.1${LOGIN_URL}" || true)
  if [ "$code" != "200" ]; then
    rm -f "$tmp"
    fail "https://127.0.0.1${LOGIN_URL} returned ${code} (want 200)"
    exit 1
  fi
  if ! cmp -s "$tmp" "${BRAND_DIR}/${BRAND_LOGIN_BANNER}"; then
    rm -f "$tmp"
    fail "Login banner HTTP 200 but body did not match ${BRAND_DIR}/${BRAND_LOGIN_BANNER}"
    exit 1
  fi
  rm -f "$tmp"
  ok "Login banner served at ${LOGIN_URL} (HTTP 200)"
  local got
  got=$(ldap_get "gacf" "zimbraSkinLogoLoginBanner")
  if [ "$got" != "$LOGIN_URL" ]; then
    fail "gacf zimbraSkinLogoLoginBanner is '${got}', expected '${LOGIN_URL}'"
    exit 1
  fi
  ok "LDAP login banner = ${LOGIN_URL}"
}

# -----------------------------------------------------------------------------
NEED_PROXY=0
NEED_MAILBOXD=0
install_brand_tree

if [ "$OS_ONLY" -eq 1 ]; then
  echo
  say "Branding OS copy complete (--os-only)"
  ok "Peer/Unpromoted: ${BRAND_DIR} ready for failover"
  info "LDAP + nginx template stay on the Promoted node (DRBD)."
  exit 0
fi

if [ ! -d /opt/zimbra ]; then
  fail "Zimbra tree missing — use --os-only on Secondary, or run on Promoted with /opt/zimbra mounted"
  exit 1
fi

patch_nginx_template
apply_chameleon_ldap
restart_zimbra_frontends
verify_brand

echo
say "Branding stage complete"
ok "${BRAND_NAME} — webmail login + mailbox UI use ${BRAND_DIR}"
info "Uninstall removes this with /etc/kin-mail (see install/kin-mail-uninstall.sh)."
info "Do not copy these files into jetty skins/; upgrades wipe that tree."
