---
- name: Include the base cluster package installation steps
  ansible.builtin.import_tasks: packages.yml
  tags: [cluster, base, packages]

- name: Include the pcsd service and hacluster account steps
  ansible.builtin.import_tasks: pcsd.yml
  tags: [cluster, base, pcsd]
