---
- name: Sertakan langkah instalasi paket SBD
  ansible.builtin.import_tasks: install.yml
  tags: [sbd, stonith, install]

- name: Sertakan langkah konfigurasi /etc/default/sbd
  ansible.builtin.import_tasks: config.yml
  tags: [sbd, stonith, config]

- name: Sertakan langkah drop-in systemd SBD
  ansible.builtin.import_tasks: dropins.yml
  tags: [sbd, stonith, dropins]

- name: Sertakan langkah resource STONITH Pacemaker
  ansible.builtin.import_tasks: stonith.yml
  tags: [sbd, stonith, pcs]

- name: Sertakan langkah verifikasi SBD dan STONITH
  ansible.builtin.import_tasks: verify.yml
  tags: [sbd, stonith, verify]
