---
- name: Include the SBD package installation steps
  ansible.builtin.import_tasks: install.yml
  tags: [sbd, stonith, install]

- name: Include the /etc/default/sbd configuration steps
  ansible.builtin.import_tasks: config.yml
  tags: [sbd, stonith, config]

- name: Include the SBD systemd drop-in steps
  ansible.builtin.import_tasks: dropins.yml
  tags: [sbd, stonith, dropins]

- name: Include the Pacemaker STONITH resource steps
  ansible.builtin.import_tasks: stonith.yml
  tags: [sbd, stonith, pcs]

- name: Include the SBD and STONITH verification steps
  ansible.builtin.import_tasks: verify.yml
  tags: [sbd, stonith, verify]
