---
- name: Include the softdog module file steps
  ansible.builtin.import_tasks: modules.yml
  tags: [softdog, modules]

- name: Include the kin-softdog unit steps
  ansible.builtin.import_tasks: service.yml
  tags: [softdog, service]

- name: Include the softdog verification steps
  ansible.builtin.import_tasks: verify.yml
  tags: [softdog, verify]
